# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: hiteshklad@gmail.com
copyright_name: java1337.com
description: "Sharing technology insights, focused on web and jvm technologies!"
baseurl: "/www.java1337.com"
url: "http://java1337.github.io"
twitter_username: java1337
github_username:  java1337
facebook_username:  hiteshlad
email_username:  hiteshklad@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
